version: '3'
services: 
  api: 
    build: 
      context: ./api
    container_name: api
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/app-api
    ports: 
      - "3000:3000"
  nginx: 
    build:
      context: ./nginx
    container_name: nginx
    depends_on: 
      - api
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/app-nginx
    ports: 
      - "80:80"
